on:
  schedule:
    - cron: "*/5 * * * *"
  push:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: pip install -r requirements.txt
      - run: python __init__.py
      - uses: actions/upload-artifact@v2
        with:
          name: results
          path: wait-times.csv
      - uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.GIST_TOKEN }}
          gist_id: 98b660129b01a5a2c050f3bab78aad70
          gist_description: "Wait times at NYC H&H testing sites. Updated about every 5 minutes. Code at https://github.com/ctbarna/covid-wait-times"
          gist_file_name: wait.csv
          file_path: ./wait-times.csv